### ISSUE TITLE
Feedback from @royf007

### ISSUE THREAD

**Issue by IAsDoubleYou** [IAsDoubleYou/ha_mysql#1]
**The original thread for this discussion can be found here: https://github.com/IAsDoubleYou/homeassistant-mysql_query/issues/9**

Hi @IAsDoubleYou, thank you for publishing the Alpha version of this custom component!  I was doing some testing, and it's working great for me 😀.  A couple of observations / comments:

1. The supplied query needs to be on a single line.  So, when I tried using the multi-line YAML syntax, i.e.:
```
query: >- 
    WITH QUERY AS (
    SELECT 123 AS Number, 'Test String' AS Value
    )
    SELECT * FROM QUERY
```
  the query fails, so it needs to be written as:

```
 query: WITH QUERY AS (SELECT 123 AS Number, 'Test String' AS Value) SELECT * FROM QUERY
```

  That's not really an issue.  Maybe something to add to the docs.

2. The **json_result** is perfect for my needs and contains the entire query result
3. If 2 queries are executed, one after another using the same sensor, and the second one has no results, then the **json_results** attribute value is not cleared.
4. In addition to **query_date** and **query_time**, it would be great to have the **executed_sql_query** as another attribute of the sensor so the **json_results** can be correlated to which SQL query was actually run to produce the results.

If I think of anything else, I'll let you know.

**Comment by IAsDoubleYou** [comment]
Hi @royf007,

thank you so much for willing to test the component and the extensive feedback you’re providing. 
I”ll work on your suggestions soon and will keep you updated. 

I've copied the issue from the MySQL query over here so it can be discussed at the right location

**Comment by IAsDoubleYou** [comment]
Hi @royf007,

Requests (2,)3 and 4 are addressed and will be released in a new version.
Regarding, the multiline issue mentioned as point 1, i have not been able to reproduce that. When i copy your example query and execute it just the way it is, i'm not experiencing any issues.
Could you please upload some screenshots of the issue?

**Comment by royf007** [comment]
Hi @IAsDoubleYou ,

Thank you so much for implementing my suggestions and for the bug fixes! The **executed_sql_query** attribute really helps!

<details>
<summary>Complex Query Example</summary>


![HA_MySQL](https://github.com/IAsDoubleYou/ha_mysql/assets/4976402/0c2b1202-46a2-437d-b126-98979e9fcba2)

</details>

So, the issue that I reported previously turned out to be a formatting issue with my YAML.  I am able to successfully execute a multi-line SQL statement that contains a WITH clause, and I'm having no issues now!
